<template>
  <div class="q-pa-md">
    <div class="q-gutter-y-md column" style="width: 300px">
      <q-form @submit.prevent="submitForm">
        <q-input v-model="newDocument.id" label="Identification Document Number" required />
        <q-input v-model="newDocument.firstName" label="First Name" required />
        <q-input v-model="newDocument.lastName" label="Last Name" required />
        <q-input v-model="newDocument.fileName" label="Name of the File" required />
        <q-input v-model="newDocument.pageCount" label="Amount of Pages" type="number" required />
        <q-input v-model="newDocument.autoGeneratedId" type="number" hint="Disable" disable />
        <q-file v-model="file" label="File" accept="*" @change="handleFileChange" />
        <q-btn type="positive" label="Submit" />
      </q-form>
      <div v-if="submissionError">
        <q-alert type="negative" dismissible>{{ submissionError }}</q-alert>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data() {
    return {
      newDocument: {
        id: '',
        firstName: '',
        lastName: '',
        fileName: '',
        pageCount: 0,
        autoGeneratedId: Math.floor(Math.random() * 1000000000),
        file: null,
      },
      file: null,
      submissionError: null,
    };
  },
  methods: {
    submitForm() {
      if (!this.validateForm()) {
        return;
      }

      this.$emit('submit-document', this.newDocument);
      this.resetForm();
    },
    handleFileChange(file) {
      this.file = file;
    },
    resetForm() {
      this.newDocument = {
        id: '',
        firstName: '',
        lastName: '',
        fileName: '',
        pageCount: 0,
        autoGeneratedId: Math.floor(Math.random() * 1000000000),
        file: null,
      };
      this.file = null;
      this.submissionError = null;
    },
    validateForm() {
      let isValid = true;
      const requiredFields = ['id', 'firstName', 'lastName', 'fileName', 'pageCount'];
      requiredFields.forEach(field => {
        if (!this.newDocument[field]) {
          isValid = false;
          this.submissionError = 'Please fill in all required fields.';
        }
      });
      return isValid;
    },
  },
};
</script>
<style scoped>

</style>
